### PR TITLE
revert to older DockerConfig struct

### PR DESCRIPTION
**Pull request by nyaaao**
Hi
I’ve tried to use you container and still got authorization errors (writing to ~/.docker/config.json)
, and it turns out that the config produced by `docker login` is slightly differs.
I was further surprised to see the right structure was being generated once. I tried to revert that change from c0118ce666d0a2f794bf7db2c2819887ec248304 and it seems to work like it should.
Disclaimer: I’m not proficient in Go to tell whether the code is good.

### CODE REVIEW

**Comment by jamiemccrindle** [comment]
Thanks for doing this! I'll review and let you know

**Comment by nyaaao** [comment]
@jamiemccrindle are there any news?

**Comment by jamiemccrindle** [comment]
Yup! Thanks for your contribution. While looking at it I recalled why I used the older format and it's because we were using this to create .dockercfg files for coreos.

I'd like to keep supporting both formats, so I've pushed a version that will detect the type of config file you're using and read / write the appropriate format. You can also explicitly set it.

**Comment by jamiemccrindle** [comment]
@nyaaao if you could test it, that would be great!

**Pull request closed without merging**
